version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/London'
    groups:
      regular-updates:
        update-types:
          - "minor"
          - "patch"
